name: Terraform PR Check

on: [pull_request]

jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
    
          - name: HashiCorp - Setup Terraform
            uses: hashicorp/setup-terraform@v3
            with:
              terraform_version: 1.7.3
    
          - name: Terraform fmt
            id: fmt
            run: terraform fmt -check -recursive
    
          - name: Terraform Init
            id: init
            run: terraform init -backend=false
    
          - name: Terraform Validate
            id: validate
            run: terraform validate -no-color
